//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableColumns
    {
        public int ID { get; set; }
        public int MenuId { get; set; }
        public string HeadText { get; set; }
        public string Name { get; set; }
        public string DataPropertyName { get; set; }
        public int Width { get; set; }
        public bool Visible { get; set; }
        public bool ReadOnly { get; set; }
        public int ColumnType { get; set; }
        public bool Resizable { get; set; }
        public int Align { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<int> MaxInputLength { get; set; }
        public int SortMode { get; set; }
        public Nullable<int> PurviewId { get; set; }
        public string Custom { get; set; }
        public string Remark { get; set; }
        public bool AllowEdit { get; set; }
        public bool AllowDelete { get; set; }
        public bool IsEnabled { get; set; }
        public int SortIndex { get; set; }
        public int DeleteMark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
